[mypy]
python_version = 3.12
mypy_path = src
packages = dav2mkv, tests
disallow_any_generics = True
disallow_any_unimported = True
disallow_any_expr = True
disallow_any_explicit = True
disallow_any_decorated = True
no_implicit_reexport = True
warn_return_any = True
strict_equality = True
warn_unused_configs = True

[mypy-tests.*]
disallow_any_decorated = False
disallow_untyped_calls = False
warn_return_any = False
disable_error_code = union-attr
disallow_any_expr = False
strict_equality = True
