[mypy]
python_version = 3.12
disallow_any_generics = True
disallow_any_unimported = True
disallow_any_expr = True
disallow_any_explicit = True
disallow_any_decorated = True
no_implicit_reexport = True
warn_return_any = True
strict_equality = True
warn_unused_configs = True
